import React, { createContext, useCallback, useContext, useMemo, useState } from "react";

type Language = "zh" | "en";

const translations = {
  zh: {
    language_zh: "中文",
    language_en: "英文",
    error_title: "错误",
    success_title: "成功",
    confirm: "确定",
    cancel: "取消",
    login_nav_title: "AllCallAll 登录",
    login_subtitle: "以邮箱为唯一地址的实时通话系统",
    login_email_label: "邮箱",
    login_password_label: "密码",
    login_button: "登录",
    login_loading: "登录中...",
    login_signup: "还没有账号？注册",
    login_failed_title: "登录失败",
    login_failed_message: "请检查邮箱和密码。",
    register_nav_title: "AllCallAll 注册",
    register_title: "创建账号",
    register_subtitle: "通过邮箱使用 AllCallAll，开启实时通信",
    register_display_name_label: "显示名称",
    register_email_label: "邮箱",
    register_password_label: "密码",
    register_button: "注册",
    register_loading: "注册中...",
    register_already: "已有账号？登录",
    register_error_missing_email: "请输入邮箱",
    register_error_invalid_email: "请输入有效的邮箱地址",
    register_error_missing_password: "请输入密码",
    register_error_password_short: "密码至少需要 8 个字符",
    register_error_missing_name: "请输入显示名称",
    register_error_check_input: "请检查输入信息",
    verify_nav_title: "邮箱验证",
    verify_title: "邮箱验证",
    verify_subtitle: "我们会向您的邮箱发送验证码",
    verify_send_code: "发送验证码",
    verify_send_loading: "发送中...",
    verify_send_success: "验证码已发送到您的邮箱",
    verify_send_failed: "发送失败",
    verify_title_code: "验证邮箱",
    verify_subtitle_code: "请输入发送到 {email} 的验证码",
    verify_code_label: "请输入验证码",
    verify_code_required: "请输入完整的6位验证码",
    verify_button: "确认验证",
    verify_loading: "验证中...",
    verify_success: "邮箱验证完成",
    verify_failed: "验证失败",
    verify_resend_success: "验证码已重新发送",
    verify_resend_failed: "重新发送失败",
    verify_resend: "未收到验证码？重新发送",
    verify_resend_countdown: "{seconds}秒后可重新发送",
    verify_change_email: "更改邮箱",
    verify_back: "返回",
    verify_code_accessibility: "验证码第 {index} 位",
    contacts_greeting: "你好, {name}",
    contacts_presence_title: "我的状态",
    contacts_title: "联系人",
    contacts_add_button: "添加联系人",
    contacts_empty: "还没有联系人，点击“添加联系人”开始吧。",
    contacts_add_title: "添加联系人",
    contacts_add_email_label: "邮箱",
    contacts_add_confirm: "添加",
    contacts_add_success: "{email} 已加入联系人。",
    contacts_add_failed: "无法添加联系人，可能已存在或输入有误。",
    contacts_remove_title: "删除联系人",
    contacts_remove_confirm: "确定删除 {name} 吗？",
    contacts_remove_failed: "删除失败，请稍后再试。",
    contacts_reload_failed: "无法加载联系人列表，请重试。",
    contacts_signal_unavailable_title: "正在重新连接",
    contacts_signal_unavailable_message: "信令服务暂时不可用，请稍后再试。",
    contacts_change_password: "改密码",
    contacts_logout: "退出登录",
    contacts_call_logs: "通话记录",
    contact_call: "呼叫",
    contact_message: "发送消息",
    contact_remove: "删除",
    presence_online: "在线",
    presence_offline: "离线",
    presence_offline_time: "离线 • {time}",
    call_status_calling: "正在呼叫 {email}",
    call_status_incoming: "{email} 呼叫你",
    call_status_in_call: "与 {email} 通话中",
    call_status_label: "状态: {status}",
    call_status_connecting: "呼叫中",
    call_status_incoming_short: "来电",
    call_status_in_call_short: "通话中",
    call_accept: "接受",
    call_reject: "拒绝",
    call_end: "结束",
    call_logs_title: "通话记录",
    call_logs_empty: "暂无通话记录。",
    call_logs_outgoing: "拨出",
    call_logs_answered: "接听",
    call_logs_missed: "未接",
    call_logs_load_failed: "无法获取通话记录，请稍后重试。",
    change_password_title: "修改密码",
    change_password_subtitle: "请输入您的当前密码和新密码",
    change_password_old_label: "当前密码 *",
    change_password_new_label: "新密码 *",
    change_password_confirm_label: "确认新密码 *",
    change_password_old_placeholder: "输入当前密码",
    change_password_new_placeholder: "输入新密码",
    change_password_confirm_placeholder: "再次输入新密码",
    change_password_required: "此字段为必填项",
    change_password_rules: "需要至少 8 个字符，必须包含字母和数字",
    change_password_valid: "✓ 密码符合要求",
    change_password_match: "✓ 两次密码一致",
    change_password_mismatch: "✗ 两次密码不一致",
    change_password_show: "显示密码",
    change_password_hide: "隐藏密码",
    change_password_button: "修改密码",
    change_password_loading: "修改中...",
    change_password_cancel: "取消",
    change_password_form_error_title: "表单错误",
    change_password_form_error_body: "请检查所有字段",
    change_password_success_title: "成功",
    change_password_success_body: "密码已成功修改",
    change_password_failed_title: "修改失败",
    change_password_failed_body: "修改密码失败，请重试",
    password_error_short: "密码至少需要 8 个字符",
    password_error_long: "密码最多 128 个字符",
    password_error_letter: "密码必需包含字母（A-Z, a-z）",
    password_error_digit: "密码必需包含数字（0-9）",
    password_error_special: "密码不能包含特殊字符或空格",
    auth_expired_title: "授权失效",
    auth_expired_body: "请先登陆",
    login_required_title: "错误",
    login_required_body: "请先登录",
    permission_error_title: "权限错误",
    permission_error_body: "无法获取权限，请检查系统设置。",
    connection_issue_title: "连接问题",
    connection_issue_body: "信令服务未连接。",
    signal_send_failed_body: "无法发送信令消息。",
    call_error_title: "呼叫错误",
    call_error_invalid_invite: "收到无效的呼叫请求",
    call_error_generic: "发生未知错误",
    call_rejected_title: "呼叫被拒绝",
    call_rejected_body: "{name} 拒绝了通话。",
    call_timeout_title: "对方无应答",
    call_timeout_body: "对方未在 60 秒内接听。",
    call_ended_title: "通话结束",
    call_ended_body: "{name} 结束了通话。",
    missed_call_title: "您有未接来电",
    missed_call_body: "您有未接来电。",
    call_in_progress_title: "提示",
    call_in_progress_body: "已有通话在进行中，请先结束该通话",
    mic_permission_title: "需要麦克风权限",
    mic_permission_body: "请在系统设置中授予麦克风或蓝牙权限。",
    call_start_failed_title: "无法发起通话",
    call_start_failed_body: "请确认麦克风未被占用或已授权。",
    call_accept_failed_title: "无法接通",
    call_accept_failed_body: "请确认麦克风或蓝牙权限已授权。",
    chat_title: "聊天",
    chat_send_button: "发送",
    chat_input_placeholder: "输入消息...",
    chat_empty: "暂无消息，开始聊天吧。",
    chat_emoji_toggle: "表情",
    chat_load_failed: "无法获取聊天记录，请稍后重试。"
  },
  en: {
    language_zh: "Chinese",
    language_en: "English",
    error_title: "Error",
    success_title: "Success",
    confirm: "OK",
    cancel: "Cancel",
    login_nav_title: "AllCallAll Login",
    login_subtitle: "Email-first calling experience",
    login_email_label: "Email",
    login_password_label: "Password",
    login_button: "Login",
    login_loading: "Logging in...",
    login_signup: "Need an account? Sign up",
    login_failed_title: "Login failed",
    login_failed_message: "Please verify your email and password.",
    register_nav_title: "AllCallAll Register",
    register_title: "Create account",
    register_subtitle: "Use AllCallAll with email and start real-time calling",
    register_display_name_label: "Display name",
    register_email_label: "Email",
    register_password_label: "Password",
    register_button: "Register",
    register_loading: "Registering...",
    register_already: "Already have an account? Login",
    register_error_missing_email: "Please enter your email",
    register_error_invalid_email: "Please enter a valid email",
    register_error_missing_password: "Please enter a password",
    register_error_password_short: "Password must be at least 8 characters",
    register_error_missing_name: "Please enter a display name",
    register_error_check_input: "Please check your input",
    verify_nav_title: "Email Verification",
    verify_title: "Email verification",
    verify_subtitle: "We will send a verification code to your email",
    verify_send_code: "Send code",
    verify_send_loading: "Sending...",
    verify_send_success: "Verification code sent to your email",
    verify_send_failed: "Send failed",
    verify_title_code: "Verify email",
    verify_subtitle_code: "Enter the code sent to {email}",
    verify_code_label: "Enter verification code",
    verify_code_required: "Please enter the full 6-digit code",
    verify_button: "Verify",
    verify_loading: "Verifying...",
    verify_success: "Email verified",
    verify_failed: "Verification failed",
    verify_resend_success: "Verification code resent",
    verify_resend_failed: "Resend failed",
    verify_resend: "Didn't receive it? Resend",
    verify_resend_countdown: "Resend available in {seconds}s",
    verify_change_email: "Change email",
    verify_back: "Back",
    verify_code_accessibility: "Verification code digit {index}",
    contacts_greeting: "Hi, {name}",
    contacts_presence_title: "My presence",
    contacts_title: "Contacts",
    contacts_add_button: "Add contact",
    contacts_empty: "No contacts yet. Tap “Add contact” to start.",
    contacts_add_title: "Add contact",
    contacts_add_email_label: "Email",
    contacts_add_confirm: "Add",
    contacts_add_success: "{email} added to contacts.",
    contacts_add_failed: "Unable to add contact. It may already exist or input is invalid.",
    contacts_remove_title: "Remove contact",
    contacts_remove_confirm: "Remove {name}?",
    contacts_remove_failed: "Remove failed. Please try again.",
    contacts_reload_failed: "Unable to load contacts. Please retry.",
    contacts_signal_unavailable_title: "Reconnecting",
    contacts_signal_unavailable_message: "Signaling is unavailable. Please try again.",
    contacts_change_password: "Change password",
    contacts_logout: "Logout",
    contacts_call_logs: "Call logs",
    contact_call: "Call",
    contact_message: "Send Messages",
    contact_remove: "Remove",
    presence_online: "Online",
    presence_offline: "Offline",
    presence_offline_time: "Offline • {time}",
    call_status_calling: "Calling {email}",
    call_status_incoming: "{email} is calling you",
    call_status_in_call: "In call with {email}",
    call_status_label: "Status: {status}",
    call_status_connecting: "Calling",
    call_status_incoming_short: "Incoming",
    call_status_in_call_short: "In call",
    call_accept: "Accept",
    call_reject: "Reject",
    call_end: "End",
    call_logs_title: "Call logs",
    call_logs_empty: "No call logs yet.",
    call_logs_outgoing: "Outgoing",
    call_logs_answered: "Answered",
    call_logs_missed: "Missed",
    call_logs_load_failed: "Unable to load call logs. Please try again.",
    change_password_title: "Change password",
    change_password_subtitle: "Enter your current and new password",
    change_password_old_label: "Current password *",
    change_password_new_label: "New password *",
    change_password_confirm_label: "Confirm new password *",
    change_password_old_placeholder: "Enter current password",
    change_password_new_placeholder: "Enter new password",
    change_password_confirm_placeholder: "Re-enter new password",
    change_password_required: "This field is required",
    change_password_rules: "At least 8 characters, must include letters and numbers",
    change_password_valid: "✓ Password looks good",
    change_password_match: "✓ Passwords match",
    change_password_mismatch: "✗ Passwords do not match",
    change_password_show: "Show password",
    change_password_hide: "Hide password",
    change_password_button: "Change password",
    change_password_loading: "Updating...",
    change_password_cancel: "Cancel",
    change_password_form_error_title: "Form error",
    change_password_form_error_body: "Please check all fields",
    change_password_success_title: "Success",
    change_password_success_body: "Password updated",
    change_password_failed_title: "Update failed",
    change_password_failed_body: "Unable to update password. Please try again.",
    password_error_short: "At least 8 characters",
    password_error_long: "At most 128 characters",
    password_error_letter: "Must include letters (A-Z, a-z)",
    password_error_digit: "Must include numbers (0-9)",
    password_error_special: "No spaces or special characters",
    auth_expired_title: "Session expired",
    auth_expired_body: "Please login first",
    login_required_title: "Error",
    login_required_body: "Please login first",
    permission_error_title: "Permission error",
    permission_error_body: "Unable to get permission: {error}",
    connection_issue_title: "Connection issue",
    connection_issue_body: "Signaling is not connected.",
    signal_send_failed_body: "Unable to send signaling message.",
    call_error_title: "Call error",
    call_error_invalid_invite: "Invalid call request received",
    call_error_generic: "Unknown error",
    call_rejected_title: "Call rejected",
    call_rejected_body: "{name} declined the call.",
    call_timeout_title: "No response",
    call_timeout_body: "The called party did not respond in 60 seconds.",
    call_ended_title: "Call ended",
    call_ended_body: "{name} ended the call.",
    missed_call_title: "Missed call",
    missed_call_body: "You have missed calls.",
    call_in_progress_title: "Heads up",
    call_in_progress_body: "A call is already in progress.",
    mic_permission_title: "Microphone permission required",
    mic_permission_body: "Please grant microphone or Bluetooth permission in system settings.",
    call_start_failed_title: "Unable to start call",
    call_start_failed_body: "Error: {error}\nPlease make sure the mic is available or permission granted.",
    call_accept_failed_title: "Unable to connect",
    call_accept_failed_body: "Please confirm mic or Bluetooth permissions are granted.",
    chat_title: "Chat",
    chat_send_button: "Send",
    chat_input_placeholder: "Type a message...",
    chat_empty: "No messages yet. Say hello!",
    chat_emoji_toggle: "Emoji",
    chat_load_failed: "Unable to load chat history. Please try again."
  }
} as const;

type TranslationKey = keyof typeof translations.en;
type TranslationParams = Record<string, string | number>;

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, params?: TranslationParams) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children
}) => {
  const [language, setLanguage] = useState<Language>("zh");

  const t = useCallback(
    (key: TranslationKey, params?: TranslationParams) => {
      let template = translations[language][key] ?? key;
      if (params) {
        Object.entries(params).forEach(([paramKey, value]) => {
          template = template.replace(
            new RegExp(`\\{${paramKey}\\}`, "g"),
            String(value)
          );
        });
      }
      return template;
    },
    [language]
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t
    }),
    [language, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return ctx;
};
